server:
  port: 9096
spring:
  datasource:
    username: sa
    password: null
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
